### ISSUE TITLE
Doesn't work with some items

### ISSUE THREAD

**Issue by DreadBoy** [GoldenDelicios/block_rotator#8]
I went through all the blocks and here's a list of blocks that don't work with this datapack:

- glazed terracotta
- dispensers
- droppers
- observers
- logs, stripped logs and wood/bark
- quartz and purpur pillars
- hay bales
- bone blocks
- stairs

I checked functions and they seem fine but I don't know a lot about mcfunctions so I must have missed something. Can you check this datapack, please?

**Comment by GoldenDelicios** [comment]
Should be fixed now. Stairs are not currently rotatable with the wrench.
